# Generated by Django 5.0.2 on 2024-02-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_rename_name_appointment_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='fullname',
        ),
    ]
